tech debt: update ledger dependencies
shapeshift/hdwallet pull request #346
Opened 2021-10-14 23:19 UTC by millsmcilroy

2021-10-15 01:02 UTC, cjthompson commented on examples/sandbox/package.json
> +    "node": "14.x"
I don't think this is accurate. You're 100% certain this doesn't run on older versions of node? I'm running node 12.x and it compiles fine for me.

2021-10-15 01:07 UTC, cjthompson requested changes
remove or change the `engines` property in `package.json`.

2021-10-15 04:17 UTC, reidrankin commented on packages/hdwallet-ledger/src/bitcoin.ts
> +export const supportedCoins = ["Testnet", "Bitcoin", "BitcoinCash", "Litecoin", "Dash", "DigiByte", "Dogecoin"];
This export is not needed since btcSupportsCoin is already available.

2021-10-15 15:56 UTC, millsmcilroy commented on packages/hdwallet-ledger-webusb/package.json
> +    "@ledgerhq/live-common": "21.8.2",
I do not like to use `^` deps with ledger dependencies because they often introduce breaking changes on patch versions that can catch us off guard

2021-10-16 02:49 UTC, reidrankin commented
(whoops, wrong branch!)

2021-10-16 03:11 UTC, reidrankin commented on packages/hdwallet-ledger/package.json
> +    "@types/ledgerhq__hw-transport": "4.21.4",
fair enough!

2021-10-16 03:35 UTC, reidrankin commented
@millsmcilroy I did some cleanup on this and added the TS magic needed to pull in the types from the ledger packages. It needed a couple of supporting PRs (#349, #350) to enable strict mode first; since we use `null` to switch to a specific set of methods in `call(null, "foo")`, `strictNullChecks` needs to be turned on so that `null` isn't treated as a member of every type.

I opened #351 separately to avoid clobbering your branch history with the extra strict-mode stuff, but if you like it IMO it'd make more sense to force-push it to this branch and use this PR instead of that one.

2021-10-18 21:51 UTC, millsmcilroy commented
Closing in favor of #351

2021-10-18 21:51 UTC, closed without merging