fix: updated intanceof checks to allow Buffer intances
shapeshift/hdwallet pull request #522
Opened 2022-04-21 21:32 UTC by theoboldfrazier

Due to polyfill of Buffer on wev2, the function `fromB64ToArray` was returning type Buffer, instead of Uint8Array. This was causing an error to be thrown and blocking decryption of a wallet.

This PR updates the checks to allow instanceof Buffer in addition to the existing ArrayBuffer and Uint8Array types.

2022-04-26 18:09 UTC, mrnerdhair requested changes
Pretty sure this is caused by jest pulling prototype shenanigans with Uint8Array which break `instanceof`. We should fix jest, or at most the return type of `fromB64ToArray()`, instead of widening the runtime checks.

2022-04-28 18:53 UTC, mrnerdhair commented
Double-checking; is this issue still relevant / can we close this?

2022-05-12 18:21 UTC, cjthompson commented
It seems to me that `Buffer` is a valid input to those functions, seeing as how no code changes were needed to support `Buffer`. I don't see a downside here.

2022-07-23 00:46 UTC, 0xApotheosis commented on packages/hdwallet-native/src/crypto/utils.ts
> +export function fromB64ToArray(str: string): Uint8Array | Buffer {
Doesn't `Buffer.from()` always return `Buffer` for all of its overloads?

2024-01-29 21:15 UTC, 0xean commented
closing as stale.

2024-01-29 21:15 UTC, closed without merging