feat: avalanche support for native wallet
shapeshift/hdwallet pull request #581
Opened 2022-10-07 12:37 UTC by chxash

This adds avalanche support for native wallet by using `_supportsEthSwitchChain` boolean.
Tested with web, I have been able to send receive `AVAX`, `WETH on Avalanche` and perform swaps `AVAX` <=> `WETH`, see screenshots attached.

![avax_sent_from_native](https://user-images.githubusercontent.com/5720927/194555243-46d52794-8177-435c-872d-d336564add7e.png)

![weth_sent_native](https://user-images.githubusercontent.com/5720927/194555264-78335b3f-7a61-4e19-829f-82f204ef87c9.png)

![avax_trade_native_1](https://user-images.githubusercontent.com/5720927/194555288-ce3a14a9-53a8-43cc-ac48-1d74f9c4b096.png)

![avax_trade_native_2](https://user-images.githubusercontent.com/5720927/194555302-8dcbf378-2272-476e-a969-bd11e07861a0.png)

![avax_trade_native_3](https://user-images.githubusercontent.com/5720927/194555319-31944502-4bd4-491a-b326-ed1867a011c5.png)

![avax_trade_native_4](https://user-images.githubusercontent.com/5720927/194555340-16cf850e-f178-46b8-a490-bef155a1d549.png)

![avax_tx_history](https://user-images.githubusercontent.com/5720927/194555353-38c5546b-063d-4dc4-8cbb-88d01f923b4e.png)

**Issue**
closes https://github.com/shapeshift/hdwallet/issues/580

2022-10-07 12:39 UTC, chxash commented on packages/hdwallet-native/src/ethereum.ts
> +    async ethGetChainId(): Promise<number | null> {
I am unsure about the necessity of doing this (enables the switch button on web, but has not real utility currently)

2022-10-19 17:49 UTC, gomesalexandre requested changes
`slip44Table` addition looks sane and really is all we should need without the `ethGetChainId` and `ethSwitchChain` methods, which are effectively wrappers around [EIP-1193](https://eips.ethereum.org/EIPS/eip-1193), the standard JSON-RPC provider API used by MetaMask and MetaMask lookalikes.

We will need a new feature detection flag for native, `_supportsEthSwitchChain` unfortunately won't work for us: it is intricately tied to some web logic to do chain switching / display chain-switching abilities as a dropdown, and native doesn't and shouldn't have any notion of a chain switch

While we initially went with `_supportsAvalanche`, the decision was then made to use chain switching as a feature detection instead (https://github.com/shapeshift/hdwallet/pull/548) which unfortunately your PR happens to unveil was a suboptimal choice - we will need both chain switching detection **and** avalanche detection

2022-10-19 17:49 UTC, gomesalexandre commented on packages/hdwallet-native/src/native.ts
> +  readonly _supportsEthSwitchChain = true;
Note, we will also need to add it in all wallets that currently support `_supportsEthSwitchChain` (in addition to `_supportsEthSwitchChain` itself)

2022-10-20 13:13 UTC, chxash commented on packages/hdwallet-native/src/native.ts
> +  readonly _supportsEthSwitchChain = true;
done !

2022-10-20 13:16 UTC, chxash commented
> `slip44Table` addition looks sane and really is all we should need without the `ethGetChainId` and `ethSwitchChain` methods, which are effectively wrappers around [EIP-1193](https://eips.ethereum.org/EIPS/eip-1193), the standard JSON-RPC provider API used by MetaMask and MetaMask lookalikes.
> 
> We will need a new feature detection flag for native, `_supportsEthSwitchChain` unfortunately won't work for us: it is intricately tied to some web logic to do chain switching / display chain-switching abilities as a dropdown, and native doesn't and shouldn't have any notion of a chain switch
> 
> While we initially went with `_supportsAvalanche`, the decision was then made to use chain switching as a feature detection instead (#548) which unfortunately your PR happens to unveil was a suboptimal choice - we will need both chain switching detection **and** avalanche detection

Fixed all of this, thanks !
Tested in web by using hdwallet locally with branch https://github.com/shapeshift/web/tree/feat_avalanche_support_native

Tested sending / receiving avax with native and metamask wallets. Swaps WETH on avalanche <> AVAX work fine.
Switch chain button is no more visible for native wallet.

![native1_avax](https://user-images.githubusercontent.com/5720927/196958776-6b773a23-0f99-4fda-a714-a428d6acd496.png)

![metamask_avax](https://user-images.githubusercontent.com/5720927/196958802-89af1dd5-7a3d-4949-9e6e-67d7fbafce12.png)

2022-10-20 14:09 UTC, gomesalexandre submitted a review, later dismissed
LGTM, tested locally and I was able to display my AVAX receive address, and after sending to it, the balance properly updates and the Tx shows up in the Tx history as a receive:

<img width="955" alt="image" src="https://user-images.githubusercontent.com/17035424/196970657-f0efdc98-ee7f-4517-b28a-4007ef31fb23.png">
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/17035424/196971178-50720221-ba01-4978-8b8d-e09b08405c39.png">

Pre-stamping this, but before this gets merged, can you run `yarn lerna:version-minor` and push the commit so this autopublishes? 🙏🏽

2022-10-20 14:14 UTC, gomesalexandre approved these changes

2022-10-20 18:44 UTC, 0xdef1cafe approved these changes

2022-10-20 18:45 UTC, merged